[package]
name = "reaching_definition"
version = "0.1.0"
authors = ["lyj <lyj@everton>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
datafrog = "2.0.1"
